[build]
builder = "nixpacks"
buildCommand = "cd frontend && npm install && npm run build"

[deploy]
startCommand = "cd frontend && npm start"
restartPolicyType = "on_failure"
restartPolicyMaxRetries = 10